apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-mysql
  namespace: ecomm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-mysql
  template:
    metadata:
      labels:
        app: notification-mysql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mysql
          image: mysql:8.0.17
          env:
            - name: MYSQL_USER
              value: root
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: 'yes'
            - name: MYSQL_DATABASE
              value: notification
          args:
            - --lower_case_table_names=1
            - --skip-ssl
            - --character_set_server=utf8mb4
            - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
---
apiVersion: v1
kind: Service
metadata:
  name: notification-mysql
  namespace: ecomm
spec:
  selector:
    app: notification-mysql
  ports:
    - port: 3306
